const Constants = {
	SET_MY_NUMBER: 'SET_MY_NUMBER',
	LOAD_MAIN_VIEW: 'LOAD_MAIN_VIEW',
	LOAD_SECOND_VIEW: 'LOAD_SECOND_VIEW',
	LOAD_THIRD_VIEW: 'LOAD_THIRD_VIEW',
	LOAD_FOURTH_VIEW: 'LOAD_FOURTH_VIEW'
};

export default Constants;
