const Constants = {
	INIT_SOMETHING: 'INIT_SOMETHING',
	SET_MY_NUMBER: 'SET_MY_NUMBER',
	LOAD_SECOND_VIEW: 'LOAD_SECOND_VIEW',
	LOAD_THIRD_VIEW: 'LOAD_THIRD_VIEW',
	LOAD_FOURTH_VIEW: 'LOAD_FOURTH_VIEW',
	LOAD_FIFTH_VIEW: 'LOAD_FIFTH_VIEW'
};

export default Constants;
